### ISSUE TITLE
SSL bug ? SSLError: [SSL] PEM lib (_ssl.c:2580)

### ISSUE THREAD

**Issue by muhahacz** [Hellowlol/HTPC-Manager#164]
Hi, thanks for this awesome fork, but here is the question:

I have selfsigned certificate generated with this oneliner:
```sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt```
but htpc manager wont start with SSL.
I have tried official htpc manager and it works, so i dont know where is the problem. Can anyone help?
Thanks

```2015-05-07 15:02:06 :: cherrypy.error :: ERROR :: [07/May/2015:15:02:06] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/opt/HTPCManager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/opt/HTPCManager/libs/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 522, in __init__
    self._context.load_cert_chain(certfile, keyfile)
SSLError: [SSL] PEM lib (_ssl.c:2580)```

**Comment by Hellowlol** [comment]
Hi! Thanks for the kind words. I have no idea why it doesnt work, until i get time to debug this you can read https://github.com/Hellowlol/HTPC-Manager/issues/109 so ssl works

**Comment by Hellowlol** [comment]
Give me a shout if you need help.

**Comment by etclarke** [comment]
Same problem here.

Traceback (most recent call last):
  File "/home/ed/.****/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/home/ed/.****/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/home/ed/.****/libs/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 522, in __init__
    self._context.load_cert_chain(certfile, keyfile)
SSLError: [SSL] PEM lib (_ssl.c:2580)

**Comment by Hellowlol** [comment]
What python version, os?
Take a screen shot of your general settings page.
Is there a .cert file in the user data folder?

**Comment by Hellowlol** [comment]
@etclarke did you read the issue I linked to?

**Comment by etclarke** [comment]
Python 2.7.9 on Ubuntu 15.04, 3.19.0-16-generic.

I am running the same cert for both sickrage and couchpotato, which worked fine until I upgraded to 15.04 but now I get this error and cannot connect to SR or CP from HTPC.

**Comment by Hellowlol** [comment]
I think there are some ssl issues in 2.7.9.

**Comment by etclarke** [comment]
I'll wait until it's patched, I don't want to break anything else.

**Comment by Hellowlol** [comment]
Ok, to fix this make sure openssl and pyopenssl install on your computer, remove app_ssl_key and app_ssl_cert from you db. Check the enable ssl button then restart htpc-manager.

**Comment by Hellowlol** [comment]
@muhahacz  @etclarke Can you update and test again?

**Comment by etclarke** [comment]
ok, htpc is starting with self-signed cert but still getting error

2015-05-08 00:51:53 :: cherrypy.error :: ERROR :: [08/May/2015:00:51:53] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/ed/.***_/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/home/ed/.**__/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/home/ed/._***/libs/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 579, in **init**
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)

and when trying to add couchpotato it errors with:

2015-05-08 00:52:52 :: modules.couchpotato :: ERROR :: Unable to connect to **********\* ('Connection aborted.', error(111, 'Connection refused'))
2015-05-08 00:52:55 :: modules.couchpotato :: ERROR :: Unable to fetch information

**Comment by Hellowlol** [comment]
Does it work with that cert on styxit version?

**Comment by etclarke** [comment]
Styxit version starts with ssl, but nothing works.

2015-05-08 10:27:26 :: htpc.settings :: DEBUG :: Unable to find the selected object: app_theme
2015-05-08 10:27:26 :: htpc.settings :: DEBUG :: Unable to find the selected object: app_theme
2015-05-08 10:27:29 :: htpc.settings :: DEBUG :: Unable to find the selected object: app_theme
2015-05-08 10:27:29 :: htpc.settings :: DEBUG :: Unable to find the selected object: app_theme
2015-05-08 10:27:29 :: htpc.settings :: DEBUG :: Unable to find the selected object: xbmc_enable........................................

And continues to:

2015-05-08 10:28:11 :: htpc.settings :: DEBUG :: Unable to find the selected object: dash_nzbget

**Comment by Hellowlol** [comment]
Do you try with the same db as you use with my version? If  thats the case try a clean install of his version (or rename the db to some other name.)

**Comment by etclarke** [comment]
I deleted the folder and cloned his repo.

**Comment by Hellowlol** [comment]
Ok, the log you showed is normal in his version. What command did you do to create the cert and key?

**Comment by etclarke** [comment]
I signed the cert using my own CA with pfsense.

**Comment by Hellowlol** [comment]
Ok. I made a cert with http://www.selfsignedcertificate.com and the one that htpc manager makes for you, both work here

**Comment by etclarke** [comment]
Have tried cert from selfsignedcertificate.com on two seperate instances of Ubuntu 15.04 and get

Traceback (most recent call last):
  File "/home/ed/.htpc/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/home/ed/.htpc/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/home/ed/.htpc/libs/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 579, in **init**
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)

Neither works.

**Comment by Hellowlol** [comment]
does sickbeard work with ssl on that computer?

**Comment by etclarke** [comment]
couchpotato, sickrage & headphones all work fine. really strange.

**Comment by Hellowlol** [comment]
Ok, I'll make a branch with cherrypy 3.7 and see if that solves the issue later today.

**Comment by Hellowlol** [comment]
@etclarke Can you try https://github.com/Hellowlol/HTPC-Manager/tree/cherrypy37 ?

**Comment by etclarke** [comment]
Ok I have installed the new repo. Headphones (which uses the same cert) is working, however, couch and sickrage are not.

2015-05-08 20:07:46 :: modules.couchpotato :: DEBUG :: Fetching information from: https://atlas:/api/df90cb6e0ec141299cdb86f4906e225a/notification.markread
2015-05-08 20:07:46 :: modules.couchpotato :: DEBUG :: Exception: ('Connection aborted.', error(111, 'Connection refused'))
2015-05-08 20:07:46 :: modules.couchpotato :: ERROR :: Unable to fetch information

2015-05-08 20:10:23 :: modules.sickrage :: ERROR :: Unable to fetch information
2015-05-08 20:10:23 :: modules.sickrage :: ERROR :: https://atlas:/api/780574f87c4b1497b3a1b03ab010fb58/?cmd=shows.stats
2015-05-08 20:10:23 :: modules.sickrage :: ERROR :: <urlopen error [Errno 111] Connection refused>

When I deleted the old git folder and cloned the new repo, the settings page still had some details in there, like username/password and my ssl location. Does htpc not store this in the root directory?

**Comment by Hellowlol** [comment]
Just to be clear, htpc manager is nworking you dont get a ssl error anymore, but you have issues with some of the modules?

You need to delete the userdata folder :)

**Comment by Hellowlol** [comment]
The reason why it fails are you settings. Look at the urls: https://atlas:/api/780574f87c4b1497b3a1b03ab010fb58/?cmd=shows.stats

**Comment by etclarke** [comment]
Yes, just sickrage and couchpotato that aren't working.

The saved data must have been browser related as I checked it with a fresh install in firefox and the data wasn't there.

I added the api manually as it fails when pressing 'test'

How come it's using that url?

**Comment by etclarke** [comment]
shit. just realised what the problem was. im an idiot, i hadn't included the port number

**Comment by Hellowlol** [comment]
Okei,can you test again with the master2 branch just to check that it wasnt some stupid settings or anything?

**Comment by etclarke** [comment]
Yes will do. Thanks for your help by the way

**Comment by etclarke** [comment]
master2 is working, it must have been settings my end. sorry about that :-(

**Comment by Hellowlol** [comment]
No worries, im just happy the master2 branch works. While i do need to update cherrypy sometime in the future ill rather wait just to make sure i havnt broken anything.

**Comment by etclarke** [comment]
glad it wasn't a complete waste of time then :-)

**Comment by Hellowlol** [comment]
@muhahacz Im gonna close this, please reopen if you still having issues
