### ISSUE TITLE
ImportError: No module named proxy

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#166]
HTPC no longer runs after latest update. Manual run from command line yields the following output:

2015-05-13 23:19:19 :: root :: INFO :: Welcome to HTPC Manager!
2015-05-13 23:19:19 :: root :: INFO :: Loglevel set to info
2015-05-13 23:19:19 :: htpc.updater :: WARNING :: /bin/sh: git: not found

None

2015-05-13 23:19:19 :: htpc.updater :: INFO :: Using SourceUpdater engine
2015-05-13 23:19:19 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-05-13 23:19:19 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-05-13 23:19:19 :: modules.stats :: ERROR :: Could't import psutil. See https://raw.githubusercontent.com/giampaolo/psutil/master/INSTALL.rst
Traceback (most recent call last):
  File "Htpc.py", line 243, in <module>
    main()
  File "Htpc.py", line 189, in main
    load_modules()
  File "Htpc.py", line 103, in load_modules
    from modules.mylar import Mylar
  File "/volume1/web/HTPC-Manager/modules/mylar.py", line 12, in <module>
    from htpc.proxy import get_image
ImportError: No module named proxy

**Comment by Hellowlol** [comment]
Sorry about that, should be fixed now
