### ISSUE TITLE
Enabling SSL crashes HTPC

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#239]
Enabled SSL with default options and restarted HTPC Manager. Now it won't connect at all.

Logs - http://pastebin.com/QpTsEKPX

**Comment by thejrose1984** [comment]
2015-07-02 22:23:47 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-07-02 22:23:47 :: root :: INFO :: Loglevel set to debug
2015-07-02 22:23:47 :: htpc.updater :: DEBUG :: Selecting Update engine.
2015-07-02 22:23:47 :: htpc.updater :: DEBUG :: Checking if git is installed
2015-07-02 22:23:47 :: htpc.updater :: DEBUG :: Running git version
2015-07-02 22:23:47 :: htpc.updater :: DEBUG :: Found git path git
2015-07-02 22:23:47 :: htpc.settings :: DEBUG :: Saving settings git_path to the database.
2015-07-02 22:23:47 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-07-02 22:23:47 :: htpc.updater :: DEBUG :: Running git rev-parse --abbrev-ref HEAD
2015-07-02 22:23:47 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-07-02 22:23:47 :: jsonrpclib.jsonrpc :: DEBUG :: Using json as JSON library
2015-07-02 22:23:47 :: apscheduler.scheduler :: DEBUG :: Looking for jobs to run
2015-07-02 22:23:47 :: apscheduler.scheduler :: DEBUG :: Next wakeup is due at 2015-07-03 04:23:47.551571-04:00 (in 21599.984110 seconds)
2015-07-02 22:23:47 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-07-02 22:23:48 :: modules.newznab :: WARNING :: No configured Indexers.
2015-07-02 22:23:48 :: modules.stats :: ERROR :: 'FreeBSD'
2015-07-02 22:23:48 :: htpc.server :: DEBUG :: Setting up to start cherrypy
2015-07-02 22:23:48 :: htpc.server :: DEBUG :: Updating cherrypy config, activating sessions and auth
2015-07-02 22:23:48 :: htpc.server :: DEBUG :: SSL is enabled
2015-07-02 22:23:48 :: htpc.server :: INFO :: Starting up webserver

---

Starting HTPC Manager on port 8085.
Start your browser and go to https://localhost:8085

---

2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Listening for SIGHUP.
2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Listening for SIGTERM.
2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Listening for SIGUSR1.
2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Bus STARTING
2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Serving on 192.168.1.216:8085
2015-07-02 22:23:48 :: cherrypy.error :: INFO :: [02/Jul/2015:22:23:48] ENGINE Bus STARTED
2015-07-02 22:23:48 :: cherrypy.error :: ERROR :: [02/Jul/2015:22:23:48] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/local/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/ssl.py", line 509, in __init__
    self._context.load_cert_chain(certfile, keyfile)
SSLError: [SSL] PEM lib (_ssl.c:2506)

**Comment by Hellowlol** [comment]
Can you take a screenshot of the about page?

**Comment by Hellowlol** [comment]
also can you take a screen shot of the the settings page (where you can see that path set for the certs/key) have you verified that the certs are valid?

**Comment by thejrose1984** [comment]
![2015-07-04 17_31_03-htpc manager](https://cloud.githubusercontent.com/assets/7573083/8509458/729acc0a-2272-11e5-9bab-06289c200ebe.png)

**Comment by thejrose1984** [comment]
Since I am running from FreeNAS, I was able to revert from snapshot since enabling SSL left my instance of HTPC-Manager crippled. The screenshot is the most recent build WITHOUT SSL

**Comment by thejrose1984** [comment]
As for the certs, I was under the impression leaving it blank would auto create self signed certs. Is this not the case?

**Comment by Hellowlol** [comment]
Yes it does, but you also have to restart htpc manager.But it does require some extra modules. Can you check that the certs/key exist in the userdata folder? Also it would be usefulll with a full log as cert/key creation is logged.

**Comment by thejrose1984** [comment]
They were created in the userdata directory. Since it's working now, I'll essentially need to break it again in order to provide the logs assuming what I provided above isn't sufficient?

**Comment by Hellowlol** [comment]
Yeah, just give me the log if you havnt wiped it :P, it you have you need to delete the cert and key in userdata, check use ssl, remove cert and key if they are present in the settings.

**Comment by thejrose1984** [comment]
Logs - http://pastebin.com/QpTsEKPX

**Comment by Hellowlol** [comment]
Is that the entire log? if it is you need to redo it. You need to restart htpc manager after you edit those settings.

**Comment by thejrose1984** [comment]
Then I'm going to have to break HTPC in order to give you want you're asking for, which is very annoying...

**Comment by Hellowlol** [comment]
Dont delete the log next time then ;)

**Comment by thejrose1984** [comment]
Didn't have a choice...I HAD TO REVERT FROM SNAPSHOT. Enabling SSL broke the entire application. It was COMPLETELY unusable :)

**Comment by thejrose1984** [comment]
FYI - I copied my config to another folder and tried to enable SSL on a fresh config...same failures...

2015-07-05 13:57:22 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-07-05 13:57:22 :: root :: INFO :: Loglevel set to info
2015-07-05 13:57:23 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-07-05 13:57:23 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-07-05 13:57:24 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-07-05 13:57:30 :: modules.newznab :: WARNING :: No configured Indexers.
2015-07-05 13:57:30 :: modules.stats :: ERROR :: 'FreeBSD'
2015-07-05 13:57:31 :: htpc.server :: INFO :: Starting up webserver

---

Starting HTPC Manager on port 8085.
Start your browser and go to http://localhost:8085

---

2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Listening for SIGHUP.
2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Listening for SIGTERM.
2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Listening for SIGUSR1.
2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Bus STARTING
2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Serving on 0.0.0.0:8085
2015-07-05 13:57:31 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:31] ENGINE Bus STARTED
2015-07-05 13:57:39 :: htpc.root :: INFO :: Shutting down HTPC Manager.
2015-07-05 13:57:39 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:39] ENGINE Bus STOPPING
2015-07-05 13:57:39 :: apscheduler.scheduler :: INFO :: Scheduler has been shut down
2015-07-05 13:57:44 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:44] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8085)) shut down
2015-07-05 13:57:44 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:44] ENGINE Stopped thread '_TimeoutMonitor'.
2015-07-05 13:57:44 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:44] ENGINE Bus STOPPED
2015-07-05 13:57:44 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:44] ENGINE Bus EXITING
2015-07-05 13:57:44 :: cherrypy.error :: INFO :: [05/Jul/2015:13:57:44] ENGINE Bus EXITED
root@htpc:/usr/local/HTPC-Manager # python Htpc.py
2015-07-05 13:58:07 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-07-05 13:58:07 :: root :: INFO :: Loglevel set to info
2015-07-05 13:58:08 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-07-05 13:58:08 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-07-05 13:58:08 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-07-05 13:58:11 :: modules.newznab :: WARNING :: No configured Indexers.
2015-07-05 13:58:12 :: modules.stats :: ERROR :: 'FreeBSD'
2015-07-05 13:58:12 :: htpc.server :: INFO :: Starting up webserver

---

Starting HTPC Manager on port 8085.
Start your browser and go to http://localhost:8085

---

2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Listening for SIGHUP.
2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Listening for SIGTERM.
2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Listening for SIGUSR1.
2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Bus STARTING
2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Serving on 0.0.0.0:8085
2015-07-05 13:58:12 :: cherrypy.error :: INFO :: [05/Jul/2015:13:58:12] ENGINE Bus STARTED
2015-07-05 13:58:16 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-05 13:58:17 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-05 13:58:28 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-05 13:58:29 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-05 13:58:40 :: htpc.root :: INFO :: Restarting HTPC Manager.
2015-07-05 13:58:45 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-07-05 13:58:45 :: root :: INFO :: Loglevel set to info
2015-07-05 13:58:45 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-07-05 13:58:45 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-07-05 13:58:46 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-07-05 13:58:48 :: modules.newznab :: WARNING :: No configured Indexers.
2015-07-05 13:58:48 :: modules.stats :: ERROR :: 'FreeBSD'
2015-07-05 13:58:49 :: htpc.server :: INFO :: Restarting to activate SSL
2015-07-05 13:58:57 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-07-05 13:58:57 :: root :: INFO :: Loglevel set to info
2015-07-05 13:58:57 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-07-05 13:58:57 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-07-05 13:58:58 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-07-05 13:59:07 :: modules.newznab :: WARNING :: No configured Indexers.
2015-07-05 13:59:08 :: modules.stats :: ERROR :: 'FreeBSD'
2015-07-05 13:59:08 :: htpc.server :: INFO :: Starting up webserver

---

Starting HTPC Manager on port 8085.
Start your browser and go to https://localhost:8085

---

2015-07-05 13:59:08 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:08] ENGINE Listening for SIGHUP.
2015-07-05 13:59:08 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:08] ENGINE Listening for SIGTERM.
2015-07-05 13:59:08 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:08] ENGINE Listening for SIGUSR1.
2015-07-05 13:59:08 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:08] ENGINE Bus STARTING
2015-07-05 13:59:08 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:08] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-07-05 13:59:09 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:09] ENGINE Serving on 0.0.0.0:8085
2015-07-05 13:59:09 :: cherrypy.error :: INFO :: [05/Jul/2015:13:59:09] ENGINE Bus STARTED
2015-07-05 13:59:09 :: cherrypy.error :: ERROR :: [05/Jul/2015:13:59:09] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/local/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/ssl.py", line 509, in __init__
    self._context.load_cert_chain(certfile, keyfile)
SSLError: [SSL] PEM lib (_ssl.c:2506)

![2015-07-05 14_02_13-htpc home - putty](https://cloud.githubusercontent.com/assets/7573083/8512731/7bf6ebc4-231e-11e5-91a1-bce21c7e05bc.png)

**Comment by Hellowlol** [comment]
Can you edit the db, and try to write the full path to the key and cert?

**Comment by thejrose1984** [comment]
Or perhaps make the SSL process more visible in the WebGUI so that enabling doesn't cause the instance to not work without needing to perform recovery?

**Comment by Hellowlol** [comment]
I cant make it anymore visable. A ssl error will fuckup cherrypy the second it starts. You dont need to do a recovery. Just shutdown htpc manager, edit the db then start it again.

**Comment by thejrose1984** [comment]
Tried that by doing the following:

`cd /usr/local/HTPC-Manager/userdata`
`sqlite3 database.db`

Attempts to edit the database results in erasing everything and needing to revert the jail from FreeNAS snapshot

**Comment by Hellowlol** [comment]
Lol

**Comment by thejrose1984** [comment]
-_-

**Comment by thejrose1984** [comment]
I'm stumped here because anything I've tried causes HTPC to crash and not having SSL seems bad because I wouldn't be able to access remotely

**Comment by Hellowlol** [comment]
Did you try to write the full path to the certs/key as a suggested? Is OpenSSL and pyopenssl installed? You can use s reverse proxy that handles Ssl for you

**Comment by thejrose1984** [comment]
You asked me to do that in the database directly and when I tried the database got erased...

**Comment by Hellowlol** [comment]
Reinstall and try again.

**Comment by Hellowlol** [comment]
@thejrose1984 can you check what version of cherrypy your running? I see that you are installing cherrypy in your wiki and there is a bug regarding ssl that is in the version between this one and 3.7. The easiest way to check is pro play just to check one of the responses from htpc manager in firebug or your browsers dev tools.

**Comment by thejrose1984** [comment]
py27-cherrypy-3.2.6 and that is the latest FreeNAS has in its repository

ran the following instead - `pip install cherrypy --upgrade` - and now running 3.8.0

**Comment by Hellowlol** [comment]
Ok. well that might be the reason why you didn't get it to work. Uninstall cherrypy so it defaults to version I have included in the source code. 

I found this comment on stackoverflow:

There was a change in version 3.2.5 that broke SSL support. This hasn't been fixed yet (as of version 3.6.0), but there is a patch suggested in issue 1298 if you need to use one of these versions.

**Comment by thejrose1984** [comment]
Won't run at all now and this is the output:

Traceback (most recent call last):
  File "Htpc.py", line 254, in <module>
    main()
  File "Htpc.py", line 241, in main
    load_modules()
  File "Htpc.py", line 68, in load_modules
    from modules.couchpotato import Couchpotato
  File "/usr/local/HTPC-Manager/modules/couchpotato.py", line 6, in <module>
    import requests
  File "/usr/local/HTPC-Manager/libs/requests/**init**.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/HTPC-Manager/libs/requests/packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/**init**.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/usr/local/lib/python2.7/site-packages/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/usr/local/lib/python2.7/site-packages/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/usr/local/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 155, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/usr/local/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so': /usr/local/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so: Undefined symbol "CRYPTO_malloc_debug_init"

**Comment by Hellowlol** [comment]
Have you uninstalled OpenSSL? Is this 3.8 or the one included?

**Comment by thejrose1984** [comment]
Yes and trying a reinstall of all HTPC requirements now...

**Comment by Hellowlol** [comment]
Remember to uninstall cherrypy, it might work but it's not tested.

**Comment by Hellowlol** [comment]
Psutil needs to be the latest version btw. I forgot to update the requirements.txt when they changed there api

**Comment by thejrose1984** [comment]
Tried a fresh install of required programs and it doesn't work at all...

**Comment by thejrose1984** [comment]
Reverting from snapshot

**Comment by thejrose1984** [comment]
Reverted to a "working" instance and ran the following:
`pip install --upgrade pip`
`pip install cherrypy --upgrade`
`pip install psutil --upgrade`

`root@htpc:/usr/local/HTPC-Manager # pip list`
`-sqlite3 (0.0.0)` This was installed through FreeNAS/FreeBSD pkg as py27-sqlite3
`cffi (1.1.2)`
`Cheetah (2.4.4)`
`CherryPy (3.8.0)`
`cryptography (0.9.1)`
`enum34 (1.0.4)`
`FormEncode (1.2.6)`
`idna (2.0)`
`ipaddress (1.0.7)`
`Markdown (2.4.1)`
`Pillow (2.8.2)`
`pip (7.1.0)`
`psutil (3.0.1)`
`pyasn1 (0.1.8)`
`pycparser (2.10)`
`pyOpenSSL (0.15.1)`
`requests (2.7.0)`
`setuptools (17.0)`
`six (1.9.0)`
`SQLObject (1.6.0)`
`wheel (0.24.0)`

Running `pip install pyOpenSSL --upgrade` based on the config above breaks it

**Comment by Hellowlol** [comment]
I'll have to check what pyopenssl I have installed. Uninstall cherrypy please. So it uses the one included in the source files

**Comment by thejrose1984** [comment]
`pip uninstall CherryPy` ran

**Comment by Hellowlol** [comment]
So does it work now?

**Comment by thejrose1984** [comment]
Does.Not.Work.

**Comment by thejrose1984** [comment]
2015-07-11 11:53:48 :: cherrypy.error :: ERROR :: [11/Jul/2015:11:53:48] ENGINE                                                                                                                                                              Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1                                                                                                                                                             837, in start
    self.tick()
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/wsgiserver2.py", line 1                                                                                                                                                             902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/HTPC-Manager/libs/cherrypy/wsgiserver/ssl_builtin.py", line 5                                                                                                                                                             2, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/local/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/ssl.py", line 522, in **init**
    self._context.load_cert_chain(certfile, keyfile)
SSLError: [SSL] PEM lib (_ssl.c:2580)

**Comment by thejrose1984** [comment]
It's the same error since the beginning. There has been absolutely no change no matter what I have done regardless of the changes to software installed and/or upgraded.

**Comment by thejrose1984** [comment]
Not sure if it's related but HTPC runs A LOT slower since removing cherrypy...

**Comment by Hellowlol** [comment]
So install it again. Just known it's untested and your might be encountering bugs :) it should be easy to revert anyway.

**Comment by thejrose1984** [comment]
Much better...now I need to figure out why images aren't being pulled from CP...

**Comment by thejrose1984** [comment]
Still doesn't work over SSL btw...

**Comment by Hellowlol** [comment]
Works fine here. I cant fix a bug that i cant find :(

**Comment by thejrose1984** [comment]
That is why you PHAIL (Ended up getting a cert and got it working only externally with a valid domain name)...  :-p

**Comment by Hellowlol** [comment]
Im not really sure what you getting at, but if you got this working you should post your solution here incase other freenas users experience the same issues

**Comment by thejrose1984** [comment]
Update Wiki

**Comment by Hellowlol** [comment]
You mentions a unit script for freenas I assume you have written one. If you have, can you make a pr for it or upload it to pastebin?

**Comment by Hellowlol** [comment]
the latest update is to cherrypy 3.8 and i think i have solved the ssl problem...

**Comment by thejrose1984** [comment]
Noticing TLS 1.0 is being used...Not sure where to make a change to use newer TLS version since there is no web server that I'm aware of (python web hosting is outside my scope of knowledge).
![2015-08-16 11_30_15-htpc manager](https://cloud.githubusercontent.com/assets/7573083/9293922/37738f0e-440a-11e5-8f7e-96b01cf988f5.png)
