### ISSUE TITLE
TV Headend gives me a 500 internal server error

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#249]
2015-07-13 21:34:01 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-07-13 21:34:01 :: root :: INFO :: Loglevel set to info
2015-07-13 21:34:01 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-07-13 21:34:01 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-07-13 21:34:01 :: modules.kodi :: INFO :: Selecting kodi server: 1
2015-07-13 21:34:01 :: modules.newznab :: WARNING :: No configured Indexers.
2015-07-13 21:34:01 :: modules.stats :: ERROR :: Required package 'smartmontools' is not installed, or 'smartctl'
component is not on the system path. Please install and try again.
2015-07-13 21:34:01 :: htpc.server :: INFO :: Starting up webserver
2015-07-13 21:34:01 :: cherrypy.error :: INFO :: [13/Jul/2015:21:34:01] ENGINE Listening for SIGTERM.
2015-07-13 21:34:01 :: cherrypy.error :: INFO :: [13/Jul/2015:21:34:01] ENGINE Bus STARTING
2015-07-13 21:34:01 :: cherrypy.error :: ERROR :: [13/Jul/2015:21:34:01] ENGINE Set handler for console events.
2015-07-13 21:34:01 :: cherrypy.error :: INFO :: [13/Jul/2015:21:34:01] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-07-13 21:34:01 :: cherrypy.error :: INFO :: [13/Jul/2015:21:34:01] ENGINE Serving on 0.0.0.0:8085
2015-07-13 21:34:01 :: cherrypy.error :: INFO :: [13/Jul/2015:21:34:01] ENGINE Bus STARTED
2015-07-13 21:34:21 :: cherrypy.error :: INFO :: [13/Jul/2015:21:34:21] ENGINE Started monitor thread 'Session cleanup'.
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:24 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:34:26 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:34:27 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:34:52 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:34:53 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:34:56 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:34:56] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:35:00 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:35:00] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:35:09 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:35:10 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:35:10 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:35:10] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:35:17 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing on system!
2015-07-13 21:37:02 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:37:02] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:37:18 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:37:19 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:37:52 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:37:53 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:37:53 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:37:53] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:40:08 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:40:09 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:40:09 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:40:09] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:40:51 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:40:52 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:42:23 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:42:23] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:42:33 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-13 21:42:34 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-13 21:42:40 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:42:40] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

2015-07-13 21:42:43 :: cherrypy.error.28462096 :: ERROR :: [13/Jul/2015:21:42:43] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 37, in index
    return htpc.LOOKUP.get_template("tvheadend.html").render(scriptname="tvheadend", webinterface=self.webinterface())
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 41, in webinterface
    port = htpc.settings,get('tvheadend_port')
NameError: global name 'get' is not defined

**Comment by fma965** [comment]
Oh yeah TVHeadend is 3.9.2827~g477feab~trusty

**Comment by Hellowlol** [comment]
Fixed or atleast that bug is fixed. I dont have a tvhead box so i have no idea if this module works or not.

**Comment by fma965** [comment]
Still doens't seem to be working, will double check git version and get you a log.

**Comment by fma965** [comment]
Oh nevermind i just git pulled and then restarted HTPC Manager now it's working :)

**Comment by Hellowlol** [comment]
Can you take a screenshot of that module? I have never seen it before :p

**Comment by fma965** [comment]
doesn't really show much but basically just shows recordings
![image](https://cloud.githubusercontent.com/assets/1707290/8679817/f294bc42-2a54-11e5-8f01-75da6970a2c4.png)
