### ISSUE TITLE
TVHeadend not showing recordings

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#252]
https://github.com/Hellowlol/HTPC-Manager/issues/249

2015-07-14 19:15:34 :: htpc.updater :: DEBUG :: Running git rev-parse --abbrev-ref HEAD
2015-07-14 19:15:34 :: htpc.updater :: DEBUG :: Running git ls-remote --heads https://github.com/Hellowlol/HTPC-Manager.git
2015-07-14 19:15:34 :: modules.plex :: DEBUG :: Getting servers from Plex
2015-07-14 19:15:34 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH \* HTTP/1.0
2015-07-14 19:15:35 :: modules.plex :: INFO :: GDM: No servers discovered
2015-07-14 19:15:37 :: cherrypy.error.47917040 :: ERROR :: [14/Jul/2015:19:15:37] HTTP Traceback (most recent call last):
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy\lib\jsontools.py", line 64, in json_handler
    value = cherrypy.serving.request._json_inner_handler(_args, *_kwargs)
  File "C:\Program Files\HTPC-Manager\libs\cherrypy_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 64, in GetChannelTags
    return self.fetch("channeltags", {'op': 'listTags'})
  File "C:\Program Files\HTPC-Manager\modules\tvheadend.py", line 97, in fetch
    strResponse = urllib2.urlopen(pRequest).read()
  File "C:\Program Files (x86)\Python\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Python\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Program Files (x86)\Python\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python\Python27\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Program Files (x86)\Python\Python27\lib\urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Program Files (x86)\Python\Python27\lib\httplib.py", line 1132, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Python\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Python\Python27\lib\httplib.py", line 441, in _read_status
    raise BadStatusLine(line)
BadStatusLine: HTTP/1.1 1 Unknown Code

Not sure you can fix this as you haven't got a TVHeadend setup but if you need me to test anything let me know :)

**Comment by Hellowlol** [comment]
It returns a unknown http code. Can you call the URL manually? What happens? Take a screenshot of the about page? Can I have the hole log with loglevel debug?

**Comment by fma965** [comment]
Hi the TVHeadend settings are 192.168.1.251 and port 9981 and when i  go to that manually i get the TVHeadend Web Interface
HTPC About
![image](https://cloud.githubusercontent.com/assets/1707290/8683845/0ce3daac-2a6d-11e5-8304-ebc5ea6deb5f.png)

TVHeadend About
![image](https://cloud.githubusercontent.com/assets/1707290/8683860/1f17d84a-2a6d-11e5-933f-a266fab3511d.png)

HTPC Log (Debug)
https://gist.github.com/Fma965/a48ab5ec0791ff0c2553

**Comment by Hellowlol** [comment]
So i added some some more debug messages. Can you update and grab me a new log? @Wizkidje I dont know if you use tvheaded or htpc manager any more but if you are, can you help us out?

**Comment by Fma965** [comment]
Yes sure, give me a few minutes :)

**Comment by fma965** [comment]
https://gist.github.com/Fma965/aafc95e42347bd51fecf

1 thing i noticed is 
2015-07-14 22:22:44 :: modules.tvheadend :: DEBUG :: url: http://192.168.1.251:9981/dvrlist_finished
when i go to 
http://192.168.1.251:9981/dvrlist_finished 
after entering user/pass it gives me 
"1 Unknown Code"
not sure if my version of tvheadend or something? tbh it's not very functional anyway so if you can't get it working its not too much of a issue.

**Comment by fma965** [comment]
if you want to add me on skype for more instant discussion it;s "Fma965_" without quotes but with underscore.

**Comment by fma965** [comment]
sorry for multiple replies.. here is the response i get from http://192.168.1.251:9981/api/channel/grid

https://gist.github.com/Fma965/634428a1b61526a5d329

**Comment by Hellowlol** [comment]
Well I can see that I have fucked up something, I'll walk the dog and update it. 
@Fma965 
Any chance you can expose this to the interwebz so i can test directly? hellowlol1@gmail.com if you want to send user name and password.

If not you need to manually check each url and paste the results for each one to a pastebin.

**Comment by fma965** [comment]
No worries, I'm not sure if it's you or tvheadend, I'm away from my computer now, I'll get it on the internet sometime tomorrow (it's midnight now) either while I'm at work or when I'm home in the evening. Easy enough to just forward the port temporarily for you. 

I will update you here / email when it's ready for you.

**Comment by fma965** [comment]
Ps: not heard the word interwebz In a while haha, I used to say that all the time.

**Comment by fma965** [comment]
Emailed @Hellowlol details!

**Comment by fma965** [comment]
Please note that i am at work so offsite from my setup but can remote in... My dad is at home and he tends to turn the router off when "no one is using it" so if you can't connect that would be why. after 4.30 (UK Time) i will be home.

**Comment by Hellowlol** [comment]
Haha, thanks. I dont have time until later anyway. :)

**Comment by Hellowlol** [comment]
New api.... 0 docs, thanks..

**Comment by fma965** [comment]
was that to TVHeadend? I thought that was pretty shit too lol

**Comment by Hellowlol** [comment]
Yeah, I have made some progress tho.

**Comment by fma965** [comment]
OK Cool, if i get time when at work (i work as a IT Technician so sometimes it's quiet other times not so much) or after work then i will work on your request for making the search bar always show :) should be relatively simple.

**Comment by Hellowlol** [comment]
I haven't really decided if I want it always visible. I will at least have it as the first thing inside the dropdown. Thanks

**Comment by fma965** [comment]
Well gonna need you to make your mind up before i work on it xD

**Comment by Hellowlol** [comment]
I have moved the search bar inside the dropdown for now. I might remove the dropdown add a site bar instead. I'll try to set off sometime to your tv headed issue today.

**Comment by fma965** [comment]
OK Cool, you won't be able to access it during the day (UK Time) though

**Comment by Hellowlol** [comment]
Closing this as tvheadend has been disabled since its broken. Hopefully somone with access can send a pr to fix it.
