### ISSUE TITLE
Does not start properly on windows 8.1

### ISSUE THREAD

**Issue by kwiksilver** [Hellowlol/HTPC-Manager#29]
System:
Windows 8.1 x64
Python 2.7.5

The styxit version launches without any issues on windows. It gives the same psutil error, and then starts up fine. Whereas this one gives the psutil error and then has the traceback with all of the issues. 

----

C:\Users\kwiksilver\Desktop\htpc\HTPC-Manager>python Htpc.py
2015-02-10 16:31:54 :: root :: INFO :: Welcome to HTPC-Manager!
2015-02-10 16:31:54 :: root :: INFO :: Loglevel set to info
2015-02-10 16:31:54 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-02-10 16:31:54 :: htpc.updater :: INFO :: Checking for updates from Git.
2015-02-10 16:31:55 :: htpc.updater :: ERROR :: Failed to get last commit from github
2015-02-10 16:31:55 :: htpc.updater :: ERROR :: Failed to determine the latest version for HTPC Manager.
2015-02-10 16:31:55 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-02-10 16:31:55 :: modules.stats :: ERROR :: Could't import psutil. See http
s://raw.githubusercontent.com/giampaolo/psutil/master/INSTALL.rst
Traceback (most recent call last):
  File "Htpc.py", line 242, in <module>
    main()
  File "Htpc.py", line 188, in main
    init_sched()
  File "Htpc.py", line 117, in init_sched
    from apscheduler.schedulers.background import BackgroundScheduler
  File "C:\Users\kwiksilver\Desktop\htpc\HTPC-Manager\libs\apscheduler\schedulers\
background.py", line 4, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "C:\Users\kwiksilver\Desktop\htpc\HTPC-Manager\libs\apscheduler\schedulers\
base.py", line 9, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

C:\Users\kwiksilver\Desktop\htpc\HTPC-Manager>

**Comment by Hellowlol** [comment]
@kwiksilver Hi! Can you grab a fresh install and try again?

**Comment by kwiksilver** [comment]
I did a fresh git clone and it worked like a charm. I also installed psutil, and I must say that it is a very useful module. Thanks.
