### ISSUE TITLE
Remote Vnstat over SSH

### ISSUE THREAD

**Issue by Mdleal** [Hellowlol/HTPC-Manager#367]
Receiving the following error when trying to grab stats from remote clients.

2015-10-23 19:52:56 :: cherrypy.error.139739294230480 :: ERROR :: [23/Oct/2015:19:52:56] HTTP
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/HTPCManager/libs/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/HTPCManager/libs/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(_args, *_kwargs)
  File "/opt/HTPCManager/libs/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/HTPCManager/modules/vnstat.py", line 213, in dumpdb
    self.version()
  File "/opt/HTPCManager/modules/vnstat.py", line 203, in version
    search = re.search(reg, self.run('--version'))
  File "/opt/HTPCManager/modules/vnstat.py", line 76, in run
    client = paramiko.SSHClient()
NameError: global name 'paramiko' is not defined
2015-10-23 19:52:56 :: cherrypy.error.139739294230480 :: ERROR :: [23/Oct/2015:19:52:56] HTTP
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/HTPCManager/libs/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/HTPCManager/libs/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/HTPCManager/modules/vnstat.py", line 174, in tr
    piped = self.run('-tr -i %s' % interface)
  File "/opt/HTPCManager/modules/vnstat.py", line 76, in run
    client = paramiko.SSHClient()
NameError: global name 'paramiko' is not defined

**Comment by Mdleal** [comment]
Ran 'pip install paramiko' and now i'm getting a new error.

2015-10-23 20:01:11 :: cherrypy.error.140444967094224 :: ERROR :: [23/Oct/2015:20:01:11] HTTP
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/HTPCManager/libs/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/HTPCManager/libs/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/HTPCManager/modules/vnstat.py", line 174, in tr
    piped = self.run('-tr -i %s' % interface)
  File "/opt/HTPCManager/modules/vnstat.py", line 79, in run
    allow_agent=False, look_for_keys=False, timeout=10)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 237, in connect
    for (family, socktype, proto, canonname, sockaddr) in socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
2015-10-23 20:01:26 :: cherrypy.error.140444967094224 :: ERROR :: [23/Oct/2015:20:01:26] HTTP
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/HTPCManager/libs/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/HTPCManager/libs/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/HTPCManager/modules/vnstat.py", line 174, in tr
    piped = self.run('-tr -i %s' % interface)
  File "/opt/HTPCManager/modules/vnstat.py", line 79, in run
    allow_agent=False, look_for_keys=False, timeout=10)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 237, in connect
    for (family, socktype, proto, canonname, sockaddr) in socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

**Comment by Mdleal** [comment]
Got it. Had the first IP/Host filled out and not the second

**Comment by Hellowlol** [comment]
So it works now?

**Comment by Mdleal** [comment]
Yes. Guess I should have done some more troubleshooting before I opened an issue.

 Can you add a note to the wiki that 'pip install paramiko' needs to ran if you are using vnstat remotely?

**Comment by Hellowlol** [comment]
It's noted in the requirements.txt :)
