### ISSUE TITLE
Sonarr error

### ISSUE THREAD

**Issue by Odinsonthor** [Hellowlol/HTPC-Manager#388]
Hello I've just installed you tool which is great 

The only issue I have is with sonarr. I ran you debug log and I get the following 

2015-11-14 10:51:52 :: htpc.root :: INFO :: Shutting down HTPC Manager.
2015-11-14 10:51:52 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:52] ENGINE Bus STOPPING
2015-11-14 10:51:52 :: apscheduler.scheduler :: INFO :: Scheduler has been shut down
2015-11-14 10:51:52 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:52] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8085)) shut down
2015-11-14 10:51:52 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:52] ENGINE Bus STOPPED
2015-11-14 10:51:52 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:52] ENGINE Bus EXITING
2015-11-14 10:51:52 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:52] ENGINE Bus EXITED
2015-11-14 10:51:59 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-11-14 10:51:59 :: root :: INFO :: Loglevel set to debug
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Selecting Update engine.
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Checking if git is installed
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Running git version
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Found git path git
2015-11-14 10:51:59 :: htpc.settings :: DEBUG :: Saving settings git_path to the database.
2015-11-14 10:51:59 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Getting current version.
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Running git rev-parse HEAD
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Current version: d96fa9fd692b76ea933b1f3c8aa57526fa9faea2
2015-11-14 10:51:59 :: htpc.updater :: DEBUG :: Running git rev-parse --abbrev-ref HEAD
2015-11-14 10:51:59 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-11-14 10:51:59 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-11-14 10:51:59 :: modules.newznab :: WARNING :: No configured Indexers.
2015-11-14 10:51:59 :: apscheduler.scheduler :: DEBUG :: Looking for jobs to run
2015-11-14 10:51:59 :: apscheduler.scheduler :: DEBUG :: Next wakeup is due at 2015-11-14 16:51:59.709000+00:00 (in 21599.953000 seconds)
2015-11-14 10:51:59 :: modules.stats :: ERROR :: Python should be executed as an administrator to smartmontools to work properly. Please, try to run python with elevated credentials.
2015-11-14 10:51:59 :: htpc.server :: DEBUG :: Setting up to start cherrypy
2015-11-14 10:51:59 :: htpc.server :: INFO :: Starting up webserver
2015-11-14 10:51:59 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:59] ENGINE Listening for SIGTERM.
2015-11-14 10:51:59 :: cherrypy.error :: INFO :: [14/Nov/2015:10:51:59] ENGINE Bus STARTING
2015-11-14 10:52:00 :: cherrypy.error :: INFO :: [14/Nov/2015:10:52:00] ENGINE Serving on http://0.0.0.0:8085
2015-11-14 10:52:00 :: cherrypy.error :: INFO :: [14/Nov/2015:10:52:00] ENGINE Bus STARTED
2015-11-14 10:52:13 :: cherrypy.error.44744600 :: ERROR :: [14/Nov/2015:10:52:13] HTTP 
Traceback (most recent call last):
  File "C:\HTPC-master\libs\cherrypy_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\HTPC-master\libs\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\HTPC-master\libs\cherrypy\lib\jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(_args, *_kwargs)
  File "C:\HTPC-master\libs\cherrypy_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "C:\HTPC-master\modules\sonarr.py", line 116, in Rootfolder
    return [folder['path'] for folder in self.fetch('Rootfolder')]
TypeError: string indices must be integers
2015-11-14 10:52:13 :: webui.console.errors :: ERROR :: {'message': u"'qlty' is undefined", 'line': u'65', 'file': u'http://localhost:8085/js/sonarr.js?1447498333.35', 'page': u'http://localhost:8085/sonarr/'}
2015-11-14 10:52:13 :: webui.console.errors :: ERROR :: {'message': u"Unable to get property 'title' of undefined or null reference", 'line': u'220', 'file': u'http://localhost:8085/js/sonarr.js?1447498333.35', 'page': u'http://localhost:8085/sonarr/'}
2015-11-14 10:52:13 :: webui.console.errors :: ERROR :: {'message': u"Unable to get property 'length' of undefined or null reference", 'line': u'9', 'file': u'http://localhost:8085/js/libs/jquery.min.js', 'page': u'http://localhost:8085/sonarr/'}
2015-11-14 10:54:11 :: cherrypy.error.44744600 :: ERROR :: [14/Nov/2015:10:54:11] HTTP 
Traceback (most recent call last):
  File "C:\HTPC-master\libs\cherrypy_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\HTPC-master\libs\cherrypy\lib\encoding.py", line 217, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\HTPC-master\libs\cherrypy\lib\jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(_args, *_kwargs)
  File "C:\HTPC-master\libs\cherrypy_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "C:\HTPC-master\modules\sonarr.py", line 116, in Rootfolder
    return [folder['path'] for folder in self.fetch('Rootfolder')]
TypeError: string indices must be integers
2015-11-14 10:54:11 :: webui.console.errors :: ERROR :: {'message': u"Unable to get property 'length' of undefined or null reference", 'line': u'9', 'file': u'http://localhost:8085/js/libs/jquery.min.js', 'page': u'http://localhost:8085/sonarr/'}
2015-11-14 10:54:11 :: webui.console.errors :: ERROR :: {'message': u"Unable to get property 'title' of undefined or null reference", 'line': u'220', 'file': u'http://localhost:8085/js/sonarr.js?1447498451.2', 'page': u'http://localhost:8085/sonarr/'}

I'm running master2

**Comment by Hellowlol** [comment]
Have you set a root folder in sonar?

**Comment by Odinsonthor** [comment]
My shows all go to a folder I originally created. Is this what you mean?

**Comment by Hellowlol** [comment]
Yeah. Can you take a screenshot of sonarip:sonarport/system/status?

**Comment by Odinsonthor** [comment]
I'm on my phone at the moment but I just remote logged in and it says

No issues with your configuration

**Comment by Hellowlol** [comment]
I'm not saying it is.. I need it see all your root folders (listed under diskspace)

**Comment by Odinsonthor** [comment]
Oh okay here is an imgur link
https://m.imgur.com/M2oZieA

**Comment by Odinsonthor** [comment]
Hi 
Was the above what you are wanting, or could u provide anymore information?

**Comment by Hellowlol** [comment]
Yes, thank you. This should work unless sonar have changed the api response.

Can you edit https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/sonarr.py#L294 replace the string inside self.fetch('.....') with self.fetch('Rootfolder') restart htpc manager then go to htpc ip:htpcport/sonarr/test and parse the response here.

**Comment by Odinsonthor** [comment]
I did that and I got a Json file which says 

{"error": "Unauthorized"}

**Comment by Hellowlol** [comment]
Check your api key then

**Comment by Odinsonthor** [comment]
I'm not using one
I'll turn it on and try again

**Comment by Odinsonthor** [comment]
Thank you it's working now 
I didn't think I was using an api as it was greyed out in the sonarr settings and when I clicked test in htpc it came up green.

Apologise and thank you for the assist.

Off topic question in what format do the scripts have to been in userdata/scripts?

**Comment by Hellowlol** [comment]
Ok, thanks for the heads up regarding the test button. I'll fix that. 

It can be a bat, sh, pl, cmd and .py.

I use a simple bat script to kill plex and start plex again.

**Comment by Odinsonthor** [comment]
How do you get it to show up
Sorry for going off topic

**Comment by Hellowlol** [comment]
They will be listed under computer stats script tab. You need to enable it in the computer stats settings
