### ISSUE TITLE
smartmontools - Python Needs to Run as Admin

### ISSUE THREAD

**Issue by monstar316** [Hellowlol/HTPC-Manager#406]
I followed the installation instructions for installing HTPC-Manager on Ubuntu 14.04 and it looked to be fine. However, when I enabled the System Info option, it came back with the following:

'smartmontools
Python should be executed as an administrator to smartmontools to work properly. Please try to run python with elevated credentials.'

How do I do that?

**Comment by Hellowlol** [comment]
Hi. You need to use sudo python htpc.py

**Comment by monstar316** [comment]
Thanks. Unforntunately, I have already tried that and I get the same issue.
This is what I get within the terminal:

sudo python /opt/HTPCManager/Htpc.py
2015-12-23 08:55:27 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager
fork
2015-12-23 08:55:27 :: root :: INFO :: Loglevel set to info
2015-12-23 08:55:27 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-12-23 08:55:27 :: apscheduler.scheduler :: INFO :: Added job
"Updater.update_needed" to job store "default"
2015-12-23 08:55:27 :: modules.kodi :: WARNING :: No configured
kodi-Servers.
2015-12-23 08:55:27 :: modules.newznab :: WARNING :: No configured Indexers.
2015-12-23 08:55:27 :: htpc.server :: INFO :: Starting up webserver

---

Starting HTPC Manager on port 8085.
Start your browser and go to http://localhost:8085

---

2015-12-23 08:55:27 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:27]
ENGINE Listening for SIGHUP.
2015-12-23 08:55:27 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:27]
ENGINE Listening for SIGTERM.
2015-12-23 08:55:27 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:27]
ENGINE Listening for SIGUSR1.
2015-12-23 08:55:27 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:27]
ENGINE Bus STARTING
2015-12-23 08:55:32 :: cherrypy.error :: ERROR :: [23/Dec/2015:08:55:32]
ENGINE Error in 'start' listener <bound method Server.start of
<cherrypy._cpserver.Server object at 0x7f9b8ebc71d0>>
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/process/wspbus.py", line 205, in
publish
    output.append(listener(_args, *_kwargs))
  File "/opt/HTPCManager/libs/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/opt/HTPCManager/libs/cherrypy/process/servers.py", line 170, in
start
    wait_for_free_port(*self.bind_addr)
  File "/opt/HTPCManager/libs/cherrypy/process/servers.py", line 439, in
wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8085 not free on '0.0.0.0'

2015-12-23 08:55:32 :: cherrypy.error :: ERROR :: [23/Dec/2015:08:55:32]
ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/opt/HTPCManager/libs/cherrypy/process/wspbus.py", line 243, in
start
    self.publish('start')
  File "/opt/HTPCManager/libs/cherrypy/process/wspbus.py", line 223, in
publish
    raise exc
ChannelFailures: IOError("Port 8085 not free on '0.0.0.0'",)

2015-12-23 08:55:32 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:32]
ENGINE Bus STOPPING
2015-12-23 08:55:32 :: apscheduler.scheduler :: INFO :: Scheduler has been
shut down
2015-12-23 08:55:32 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:32]
ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8085))
already shut down
2015-12-23 08:55:32 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:32]
ENGINE Bus STOPPED
2015-12-23 08:55:32 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:32]
ENGINE Bus EXITING
2015-12-23 08:55:32 :: cherrypy.error :: INFO :: [23/Dec/2015:08:55:32]
ENGINE Bus EXITED

**Comment by Hellowlol** [comment]
Is something else running on port 8085? Says it not free. There is nothing in the logs that related to smartmoontools here. What guide did you follow?

**Comment by monstar316** [comment]
Nothing else runs on that port so it's a bit weird it's saying there is.
Unless, it's because a non-root version of the python is running already
and it's not being detected when I try to run a root version?

However, I restarted my server (for the 50th time!!!) and now it works.
It's now letting me see System Info, including the S.M.A.R.T feature. No
idea why it wouldn't work after the other restarts. Thanks anyway for the
help.

**Comment by Hellowlol** [comment]
I wasn't much of help but thanks anyway ;)
