### ISSUE TITLE
Kodi server connection test gives false positive

### ISSUE THREAD

**Issue by laur89** [Hellowlol/HTPC-Manager#424]
When going to the Kodi server connection setting menu (http://localhost:8085/settings/#kodi_update_server), and only defining the 'IP' value (with localhost or 127.0.0.1), then the 'Test' functionality gives false-positive. In the logs it reads:

```
2016-01-28 21:44:54 :: modules.kodi :: DEBUG :: Testing kodi connectivity
2016-01-28 21:44:54 :: modules.kodi :: DEBUG :: Trying to contact kodi via localhost:
```

ie no exceptions, yet no success either, but the 'Test' button colors green as if the test was successful.
Using any other port than empty or 80 results in failure:

```
2016-01-28 21:48:22 :: modules.kodi :: DEBUG :: Testing kodi connectivity
2016-01-28 21:48:22 :: modules.kodi :: DEBUG :: Trying to contact kodi via localhost:9999
2016-01-28 21:48:22 :: modules.kodi :: ERROR :: [Errno 111] Connection refused
Traceback (most recent call last):
File "/opt/HTPCManager2/modules/kodi.py", line 217, in ping
    return kodi.XBMC.GetInfoLabels(labels=["Network.MacAddress"])
File "/opt/HTPCManager2/libs/jsonrpclib/jsonrpc.py", line 567, in __call__
    return self.__send(self.__name, kwargs)
File "/opt/HTPCManager2/libs/jsonrpclib/jsonrpc.py", line 444, in _request
    response = self._run_request(request)
File "/opt/HTPCManager2/libs/jsonrpclib/jsonrpc.py", line 477, in _run_request
    verbose=self.__verbose
File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
File "/opt/HTPCManager2/libs/jsonrpclib/jsonrpc.py", line 351, in send_content
    connection.endheaders()
File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2016-01-28 21:48:22 :: modules.kodi :: ERROR :: Unable to contact kodi via localhost:9999
```

In the excerpt above, port 9999 was tested, which was explicitly defined in kodi's advancedsettings.xml:

```
<advancedsettings>
    <jsonrpc>
        <tcpport>9999</tcpport>
    </jsonrpc>
</advancedsettings>
```

At the moment I'm unable to bind HTPC-M with Kodi setup anyways, but that's probably related to configuration issues; have yet to come across manual explaining htpc configuration.

Both HTPC-Manager and Kodi are running on 1st gen Raspberry Pi B and DietPie.
uname -a:

```
Linux DietPi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
```

kodi -v:

```
14.2 Git:7cc53a9 Media Center Kodi
```

**Comment by Hellowlol** [comment]
Thanks for the detailed report, we are using the webserver not the tcp port.

**Comment by laur89** [comment]
That explains a lot. But this means HTPC should need no configuring when it comes to connecting to Kodi, does it (given webserver is running on port 80 on the same box)?

**Comment by Hellowlol** [comment]
I haven't really tried but i think you can omit the port if its 80. You should always use the ips and not loop back og local host since that will break link in the interface.

**Comment by laur89** [comment]
Tried connecting against **127.0.0.1** with both port field left empty and set to 80, but no joy (see the first log excerpt in the first post).
Note that kodi's own web interface is accessible over port 80.

**Comment by Hellowlol** [comment]
Thats the loopback adress, try the real ip of that computer. Please provide a debug log. :)

**Comment by laur89** [comment]
I'll do that once I get back home, sorry. I'm also 99% sure the issue is in misconfig, but couldn't find any documentation regarding this topic.

> try the real ip of that computer.

Remember seeing this instruction somewhere; assumed it meant defining **127.0.0.1** instead of **localhost**. Thanks for clearing this one up, will get back once tested.

**Comment by laur89** [comment]
Sorry for the late reply. That was exactly the case - IP had to be defined with the actual ip, not loopback (including 127.0.0.1). Case closed and many thanks!

**Comment by Hellowlol** [comment]
Im glad you got it working!
