### ISSUE TITLE
pyopenSSL Cherrypy issues

### ISSUE THREAD

**Issue by GTunney** [Hellowlol/HTPC-Manager#457]
I updated my python to a newer version the other day but I'm now having issues with HTPC-Manager when SSL is enabled. OpenSSL is installed and is working fine for Sab, Couch, Sickrage and Headphones.

 Python Version:    2.7.11 (default, Feb 17 2016, 07:58:43) [GCC 4.3.6]
 SSL Version:   OpenSSL 1.0.2f 28 Jan 2016

`2016-04-18 08:33:04 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2016-04-18 08:33:04 :: root :: INFO :: Loglevel set to debug
2016-04-18 08:33:04 :: htpc.updater :: DEBUG :: Selecting Update engine.
2016-04-18 08:33:04 :: htpc.updater :: DEBUG :: Checking if git is installed
2016-04-18 08:33:05 :: htpc.updater :: DEBUG :: Running git version
2016-04-18 08:33:05 :: htpc.updater :: DEBUG :: Found git path git
2016-04-18 08:33:05 :: htpc.settings :: DEBUG :: Saving settings git_path to the database.
2016-04-18 08:33:05 :: htpc.updater :: INFO :: Using GitUpdater engine
2016-04-18 08:33:05 :: htpc.updater :: DEBUG :: Getting current version.
2016-04-18 08:33:05 :: htpc.updater :: DEBUG :: Running git rev-parse HEAD
2016-04-18 08:33:05 :: htpc.updater :: DEBUG :: Current version: c9db507c6dfab949ff52659180b289dc72d4650c
2016-04-18 08:33:05 :: htpc.updater :: DEBUG :: Running git rev-parse --abbrev-ref HEAD
2016-04-18 08:33:05 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2016-04-18 08:33:05 :: modules.kodi :: ERROR :: Invalid server. Selecting first Available.
2016-04-18 08:33:05 :: apscheduler.scheduler :: DEBUG :: Looking for jobs to run
2016-04-18 08:33:05 :: apscheduler.scheduler :: DEBUG :: Next wakeup is due at 2016-04-18 14:33:05.457086+01:00 (in 21599.952968 seconds)
2016-04-18 08:33:05 :: htpc.settings :: DEBUG :: Saving settings newznab_current_indexer to the database.
2016-04-18 08:33:05 :: modules.stats :: ERROR :: Required package 'smartmontools' is not installed, or 'smartctl'
component is not on the system path. Please install and try again.
2016-04-18 08:33:06 :: htpc.server :: DEBUG :: Setting up to start cherrypy
2016-04-18 08:33:07 :: htpc.server :: DEBUG :: Updating cherrypy config, activating sessions and auth
2016-04-18 08:33:07 :: htpc.server :: DEBUG :: There isnt any certificate or key, trying to make them
2016-04-18 08:33:07 :: htpc.helpers :: ERROR :: No module named _openssl
2016-04-18 08:33:07 :: htpc.helpers :: ERROR :: You need pyopenssl and OpenSSL to make a cert
2016-04-18 08:33:07 :: htpc.server :: DEBUG :: SSL is enabled
2016-04-18 08:33:07 :: htpc.server :: INFO :: Starting up webserver
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Listening for SIGHUP.
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Listening for SIGTERM.
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Listening for SIGUSR1.
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Bus STARTING
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE PID 3779 written to '/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/HTPC-Manager.pid'.
2016-04-18 08:33:07 :: cherrypy.error :: ERROR :: [18/Apr/2016:08:33:07] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0xf68b31ec>>
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(_args, *_kwargs))
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/_cpserver.py", line 167, in start
    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/_cpserver.py", line 158, in httpserver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/_cpwsgi_server.py", line 64, in __init__
    self.server_adapter.ssl_certificate_chain)
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/wsgiserver/ssl_pyopenssl.py", line 169, in **init**
    raise ImportError("You must install pyOpenSSL to use HTTPS.")
ImportError: You must install pyOpenSSL to use HTTPS.

2016-04-18 08:33:07 :: cherrypy.error :: ERROR :: [18/Apr/2016:08:33:07] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/libs/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: ImportError('You must install pyOpenSSL to use HTTPS.',)

2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Bus STOPPING
2016-04-18 08:33:07 :: apscheduler.scheduler :: INFO :: Scheduler has been shut down
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE HTTP Server None already shut down
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Bus STOPPED
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Bus EXITING
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE PID file removed: '/share/CACHEDEV1_DATA/.qpkg/HTPC-Manager/HTPC-Manager.pid'.
2016-04-18 08:33:07 :: cherrypy.error :: INFO :: [18/Apr/2016:08:33:07] ENGINE Bus EXITED`

**Comment by Hellowlol** [comment]
Thanks for the log. Can you add the rest of the info as explained in issue guidelines?

**Comment by GTunney** [comment]
What did you do? Upgraded Python
What happened? HTPC Manager will not start
What did you expect to happen? HTPC Manager to start
Which browser, including version? All browsers

**Comment by Hellowlol** [comment]
What os? Freenas?

**Comment by GTunney** [comment]
Linux-3.12.6-x86_64-with-glibc2.2.5

QNAP TS-451

**Comment by Hellowlol** [comment]
Awesome, thanks. Can you also post the results from pip list

**Comment by GTunney** [comment]
# pip list

cffi (1.5.2)
cryptography (1.3.1)
enum34 (1.1.2)
idna (2.0)
ipaddress (1.0.15)
Pillow (2.8.1)
pip (8.1.1)
ply (3.8)
psutil (4.1.0)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (0.15.1)
setuptools (20.2.2)
six (1.10.0)

**Comment by Hellowlol** [comment]
Ssl works fine where. I think you should raise this issue with whoever made the package. I suspect there are some issues with the Python installation.

**Comment by GTunney** [comment]
Hi the person who packaged python has also packaged HTPC-Manager with all modules embedded so i've switched to using that. Thanks for your help
