### ISSUE TITLE
Smartmontools index out of range

### ISSUE THREAD

**Issue by acdcfanbill** [Hellowlol/HTPC-Manager#472]
I've got an error with smartmontools and HTPC-Manager.  Ubuntu only had smartmontools 5.41 in the repos so I compiled and installed the latest version (6.5) from source.  I runs fine from command line.

smartctl pastebin: http://pastebin.com/yzPRyuwy

I get an error in HTPC Manager though.

```
2016-06-01 11:20:29 :: modules.stats :: ERROR :: Error Pulling S.M.A.R.T. data list index out of range
Traceback (most recent call last):
    File "/home/bill-nas/.HTPCManager/modules/stats.py", line 527, in smart_info
        devlist = DeviceList()
    File "/home/bill-nas/.HTPCManager/libs/pySMART/device_list.py", line 51, in __init__
        self._initialize()
    File "/home/bill-nas/.HTPCManager/libs/pySMART/device_list.py", line 106, in _initialize
        self.devices.append(Device(name))
    File "/home/bill-nas/.HTPCManager/libs/pySMART/device.py", line 140, in __init__
        self.update()
    File "/home/bill-nas/.HTPCManager/libs/pySMART/device.py", line 482, in update
        self.serial = line.split(':')[1].split()[0].rstrip()
IndexError: list index out of range`
```

Log since last start: http://pastebin.com/ZPKunyHs

HTPC Manager is running as root via a init.d script.  It's the latest release on master2

```
commit 46a499987f4f9d4df7ac3ffb8a4b39bc1328ab5e
Author: Hellowlol <hellowlol1@gmail.com>
Date:   Wed Jun 1 15:54:09 2016 +0200
```

I'm running Ubuntu 12.04 for an OS with python 2.7.3 running htpcmanager.

I guess the main thing that I could think of that would be the problem would be that I have some hdds on a rocketraid card in jbod mode and the rocketraid card clobbers the SMART info.  Do all hdds have to report properly for it to work, or would it just ignore any that didn't return relevant info?

Here's output from one of the drives behind the rocketraid card.

```
bill-nas@ubuntu-nas:~$ sudo smartctl -a /dev/sdf
smartctl 6.5 2016-05-07 r4318 [x86_64-linux-3.2.0-23-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HPT
Product:              DISK_6_0
Revision:             4.00
User Capacity:        1,000,123,400,192 bytes [1.00 TB]
Logical block size:   512 bytes
Logical Unit id:      0x00193c0000000000
Serial number:
Device type:          disk
Local Time is:        Wed Jun  1 11:35:07 2016 CDT
SMART support is:     Unavailable - device lacks SMART capability.

=== START OF READ SMART DATA SECTION ===
Request Sense failed, [Input/output error]
Error Counter logging not supported


[GLTSD (Global Logging Target Save Disable) set. Enable Save with '-S on']
Device does not support Self Test logging
```

**Comment by Hellowlol** [comment]
Hi! There isnt away to fix this unless we manually patch pysmart :(

**Comment by acdcfanbill** [comment]
Something like a whitelist of device names: /dev/sda /dev/sdb... 

So it would be like the mountpoints for monitoring?

**Comment by Hellowlol** [comment]
Yeah, we could try that.
