### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by cesalo** [Hellowlol/HTPC-Manager#479]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [2f3d21cd395ea743d37373c6b4f95deae1384ec6] Version
- [master2] Branch
- [ ] Commit hash
- [QNAP NAS: Linux QNAP-TS651-1 3.12.6 ] Operating system
- [2.7.9 ] Python version
- What you did?

I noticed that there was an update so I did it from the app itself. After this last update it didn't start.
- [ ] What happened?

It doesn't start. Error is the following and it stops there:
'''
[/share/CACHEDEV1_DATA/.qpkg/HTPCManager/bin] # /etc/init.d/HTPCManager.sh restart
HTPCManager is stopped.
2016-06-13 09:27:49 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2016-06-13 09:27:49 :: root :: INFO :: Loglevel set to info
2016-06-13 09:27:49 :: htpc.updater :: INFO :: Using SourceUpdater engine
2016-06-13 09:27:49 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2016-06-13 09:27:49 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2016-06-13 09:27:49 :: modules.newznab :: WARNING :: No configured Indexers.
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/HTPCManager/HTPC-Manager-master/Htpc.py", line 261, in <module>
    main()
  File "/share/CACHEDEV1_DATA/.qpkg/HTPCManager/HTPC-Manager-master/Htpc.py", line 246, in main
    load_modules()
  File "/share/CACHEDEV1_DATA/.qpkg/HTPCManager/HTPC-Manager-master/Htpc.py", line 96, in load_modules
    from modules.sonarr import Sonarr
  File "/share/CACHEDEV1_DATA/.qpkg/HTPCManager/HTPC-Manager-master/modules/sonarr.py", line 162
    d = {}
         ^
IndentationError: unindent does not match any outer indentation level
'''
- [ ] What you expected?

Updated version and that the app started.
- [ ] How can we reproduce your issue?

Every time I try to start it.
- [ ] What are your (relevant) settings?

I have configured: Mylar / Plex / Sickbeard / Couchpotato
- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

https://gist.github.com/cesalo/563a94bff1f92485771a2262c681f527

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

**Comment by Hellowlol** [comment]
Use git pull to fix the issue, sorry for breaking htpc manger
