### ISSUE TITLE
TVHeadend connection error

### ISSUE THREAD

**Issue by Stealth1081** [Hellowlol/HTPC-Manager#534]
Please forgive any information or layout errors, first time posting an issue on github.

HTPC-Manager seems to not be able to connect to tvheadend.

- [ ] Branch: master2
- [ ] Commit hash: 366a407d325ddad87b3c25b270b502877a4a2c8a
- [ ] Operating system: Linux-4.9.8-unRAID-x86_64-with - Running in a docker
- [ ] Python version: 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
- [ ] What you did?: Tried out tvheadend module
- [ ] What happened?: Nothing happened, just a spinning circle
- [ ] What are your (relevant) settings?: HTS Tvheadend 4.1-2425~gcf818c05b

Below is a the only log file i could find specific to HTPC-Manager

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error.
http://pastebin.com/m4567eTc

Specific error seems to be 

TypeError: not enough arguments for format string
2017-02-14 22:13:41 :: cherrypy.error.47333621572752 :: ERROR :: [14/Feb/2017:22:13:41] HTTP

Traceback (most recent call last):
File "/app/htpcmanager/libs/cherrypy/_cprequest.py", line 670, in respond
response.body = self.handler()
File "/app/htpcmanager/libs/cherrypy/lib/encoding.py", line 217, in __call__
self.body = self.oldhandler(*args, **kwargs)
File "/app/htpcmanager/libs/cherrypy/lib/jsontools.py", line 63, in json_handler
value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
File "/app/htpcmanager/libs/cherrypy/_cpdispatch.py", line 61, in __call__
return self.callable(*self.args, **self.kwargs)
File "/app/htpcmanager/modules/tvheadend.py", line 83, in DVRList
return self.fetch("api/dvr/entry/grid_" + strType, None)
File "/app/htpcmanager/modules/tvheadend.py", line 113, in fetch
self.logger.error('%s %s failed error: %s' % strQuery, rgpData, e)

I don't understand the error and it could be something i did wrong, apologies if it is.

**Comment by Hellowlol** [comment]
I can fix the error that is logged but I still think this module is broken. I don't have a tvcard so I have no way to test this.

**Comment by Stealth1081** [comment]
Hi thanks for the reply.

If you think the module is broken i guess it is not worth fixing. If its an easy fix and you have the time i can provide log files and happy to test the functionality if it helps others.
