### ISSUE TITLE
Feature request VNSTAT in dashboard

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#9]
I use VNSTAT on PFSense to track my usage. Anyway to make a simple interface that would pull in Daily/Monthly/Yearly totals of Usage? Something like this implementation - https://github.com/lienma/UpsBoard

**Comment by elRadix** [comment]
+1 like this one

**Comment by Hellowlol** [comment]
@smdion @elRadix Im working on this request. I couldnt find a link to a demo page or a picture to upsboard. How do you want it?

**Comment by smdion** [comment]
This is how UpStatsBoard Implemented it

Config Items
			"maxSpeed": [60, 4],
			"interface": "em0",
			"vnstatDBDirectory": "/home/vnstat",

Detail Pane:
http://imgur.com/SB9CvjO

Overview:
http://imgur.com/WDkrFvr
Left bar is download, right bar is upload. And it shows the percentage of use based on the defined max-speed

**Comment by smdion** [comment]
oh.. and thank you!

**Comment by Hellowlol** [comment]
This will not use a db, but pipe it from ssh.

**Comment by smdion** [comment]
I guess it makes sense not to have a local VN stat running.

**Comment by Hellowlol** [comment]
@smdion any chance you can vnstat -dumpdb --xml and paste the content here. It would be great to have some data for the chart(s)

**Comment by elRadix** [comment]
I have vnstat running om my linux machine
http://www.thegeekstuff.com/2011/11/vnstat-network-traffic-monitor/


this is the frontend
http://www.sqweek.com/sqweek/?p=1

**Comment by Hellowlol** [comment]
is that the same computer as HTPC manager runs on? If not I'll add option so we don't use ssh

**Comment by elRadix** [comment]
yes indeed on the same machine, in fact I have it running on a synology nas, no need to ssh in this case.

**Comment by smdion** [comment]
I ran this command

vnstat --dbdir /home/vnstat -i em0 --xml

directly on my box that has VNSTAT going (PFSense) and got this output: http://pastebin.com/gDEQxkh7

Your requested command errored out

**Comment by smdion** [comment]
UpStats board also runs this command to get current data

vnstat --dbdir /home/vnstat -i em0 -tr

Output: http://pastebin.com/p9rFUGbQ

You may want to make the "/home/vnstat" and "em0" a variable so the user can tell sshd where the location of the database is on the remote server and what the name of the interface is.

**Comment by smdion** [comment]
Don't know if this would be of any help

https://github.com/lienma/UpsBoard/blob/master/core/stats/bandwidth.js

**Comment by Hellowlol** [comment]
The command I gave works fine on my rpi. But I can always allow the user to choose command to run.

**Comment by Hellowlol** [comment]
I think it will I'm awful at js

**Comment by elRadix** [comment]
would that help to call vnstat through php, i am not a dev :-)
https://github.com/bjd/vnstat-php-frontend

**Comment by Hellowlol** [comment]
No worries, I'll manage thanks for the link.

**Comment by Hellowlol** [comment]
@smdion, @elRadix What about something like this? ![image](https://cloud.githubusercontent.com/assets/1214134/5697392/3970a3d4-99ef-11e4-84db-093e6d1357b8.png)
Still need some work but you get the idea

**Comment by smdion** [comment]
Looks really nice.  Like the direction you are going.  Maybe a quick summary of "today", "this month" "this year"?

**Comment by Hellowlol** [comment]
Yeah, the pic above is last 12 months, 30 days, 24 hours. A summary would be be nice! On the dash i was thinking about adding current speed, usage so far this month and vs data cap.

**Comment by elRadix** [comment]
and also by interface eth0/1 or bond0 or wlan0 if that is possible or at least an option to select the interface you want to get summarized

**Comment by Hellowlol** [comment]
@elRadix  I would like to get stats for all if possible. Any chance you have several interfaces? Can you dump the db as xml and put in on pastebin so i can test?

**Comment by Hellowlol** [comment]
Sorry for bugging your guy so much with this, but since i dont use vnstat is need to have some data to test with :P

**Comment by elRadix** [comment]
happy to support you!!
here is it http://pastebin.com/b1CpGc99

**Comment by Hellowlol** [comment]
Awesome! Ill see if i cant loop each interface and make a charts and a summary based on that.

**Comment by Hellowlol** [comment]
@elRadix @smdion Any chance you can test the vnstat branch and see how it goes?

**Comment by smdion** [comment]
I need to install Paramiko on my docker... let me update and re-test

**Comment by Hellowlol** [comment]
it shouldnt be needed if the docker has access to a shell. i just push a fix for that.

**Comment by smdion** [comment]
2015-01-15 16:21:29 :: cherrypy.error.47049172349136 :: ERROR :: [15/Jan/2015:16:21:29] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 151, in tr
    piped = self.run('-tr')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 67, in run
    client = paramiko.Transport((hostname, 22))
NameError: global name 'paramiko' is not defined

After last update

**Comment by smdion** [comment]
I'm pushing paramiko install on my docker.. so we'll see what that does.  Small config change.  Maybe add option for non-default SSH port?  I don't need it, but someone may.

**Comment by Hellowlol** [comment]
Does any change there ssh port ? :o, np ill add that

**Comment by Hellowlol** [comment]
I think the error is becase the ssh is checked of. can you uncheck it?

**Comment by smdion** [comment]
Its unchecked, but with my vnstat database on a different IP its not pulling anything. No more error though ;)

**Comment by Hellowlol** [comment]
Ah, i get it.. i need to check that aswell can you try the ssh option?

**Comment by smdion** [comment]
I installed paramiko and now I have this... with the box checked


2015-01-15 16:37:52 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 16:37:53 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 16:37:53 :: modules.vnstat :: ERROR :: ssh failed
2015-01-15 16:37:53 :: modules.vnstat :: ERROR ::

**Comment by smdion** [comment]
2015-01-15 16:37:52 :: cherrypy.error.47174697660624 :: ERROR :: [15/Jan/2015:16:37:52] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 173, in dumpdb
    return self.run('--dumpdb --xml')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 92, in run
    return xmltodict.parse(''.join(stdout_data))
  File "/opt/HTPC-Manager-0.11.0/libs/xmltodict.py", line 251, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

**Comment by Hellowlol** [comment]
crap, i just noticed that --dumpdb was renamed to --exportdb

**Comment by Hellowlol** [comment]
Okei, can you test again, now with ssh enabled? it will now require paramiko (for now)

**Comment by smdion** [comment]
Its on my docker, so no issue.  Getting this now:

2015-01-15 17:00:34 :: cherrypy.error.47057794818256 :: ERROR :: [15/Jan/2015:17:00:34] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 161, in tr
    piped = self.run('-tr')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 67, in run
    client = paramiko.Transport((hostname, port))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 217, in __init__
    retry_on_signal(lambda: sock.connect((hostname, port)))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 217, in <lambda>
    retry_on_signal(lambda: sock.connect((hostname, port)))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required

**Comment by Hellowlol** [comment]
bah, try again?

**Comment by smdion** [comment]
Its so much better debugging other peoples code when I don't ahve to fix it ;)

2015-01-15 17:05:04 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:05:04 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:05:04 :: modules.vnstat :: ERROR :: ssh failed
2015-01-15 17:05:04 :: modules.vnstat :: ERROR :: 
2015-01-15 17:05:04 :: cherrypy.error.47065202286800 :: ERROR :: [15/Jan/2015:17:05:04] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 187, in dumpdb
    return self.run('--exportdb --xml')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 96, in run
    return xmltodict.parse(''.join(stdout_data))
  File "/opt/HTPC-Manager-0.11.0/libs/xmltodict.py", line 251, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

2015-01-15 17:05:04 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:05:05 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:05:05 :: modules.vnstat :: ERROR :: ssh failed
2015-01-15 17:05:05 :: modules.vnstat :: ERROR ::

**Comment by Hellowlol** [comment]
Well it works fine here :( can you run --exportdb --xml from the command line? and if it work paste it on pastebin?

**Comment by smdion** [comment]
ah crap.  I'm on version 1.11 which is still -dumpdb.  Let me figure out how to update my PFSense box.

**Comment by Hellowlol** [comment]
nvm ill just change it, sec

**Comment by smdion** [comment]
What if others are on 1.12?

**Comment by Hellowlol** [comment]
dunno, i had trouble with --exportdb as well and dumpdb works fine so lets stick with that for now.

**Comment by Hellowlol** [comment]
again?

**Comment by Hellowlol** [comment]
Ill find a solution for that later, like asking for the version then choose what command to run. Or something

**Comment by smdion** [comment]
2015-01-15 17:15:18 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:15:18 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:15:18 :: modules.vnstat :: ERROR :: ssh failed
2015-01-15 17:15:18 :: modules.vnstat :: ERROR :: 
2015-01-15 17:15:18 :: cherrypy.error.47568223989968 :: ERROR :: [15/Jan/2015:17:15:18] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 187, in dumpdb
    return self.run('--dumpdb --xml')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 96, in run
    return xmltodict.parse(''.join(stdout_data))
  File "/opt/HTPC-Manager-0.11.0/libs/xmltodict.py", line 251, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

2015-01-15 17:15:18 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:15:18 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:15:19 :: modules.vnstat :: ERROR :: ssh failed
2015-01-15 17:15:19 :: modules.vnstat :: ERROR :: 



my dump - http://pastebin.com/vcDpxVCN

**Comment by Hellowlol** [comment]
again? :P

**Comment by smdion** [comment]
2015-01-15 17:20:04 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:20:04 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:20:04 :: cherrypy.error.47227981144272 :: ERROR :: [15/Jan/2015:17:20:04] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 187, in dumpdb
    return self.run('--dumpdb --xml')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 96, in run
    return xmltodict.parse(''.join(stdout_data))
  File "/opt/HTPC-Manager-0.11.0/libs/xmltodict.py", line 251, in parse
    parser.Parse(xml_input, True)
ExpatError: unclosed token: line 79, column 58

2015-01-15 17:20:04 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:20:04 :: paramiko.transport :: INFO :: Authentication (password) successful!

**Comment by Hellowlol** [comment]
Im gonna kill something.. Well i guess i need a library that can handle errors in the xml.

**Comment by smdion** [comment]
Paypal address I can send beer money too ;)

**Comment by smdion** [comment]
Also... live bandwidth is working.

http://i.imgur.com/STBOQph.png

**Comment by Hellowlol** [comment]
Atleast something is working

**Comment by Hellowlol** [comment]
Okei, can you try one last time (for now.. :D )

**Comment by smdion** [comment]
Don't hurt me...

2015-01-15 17:34:40 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:34:40 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:34:40 :: cherrypy.error.47884522496208 :: ERROR :: [15/Jan/2015:17:34:40] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 187, in dumpdb
    return self.run('--dumpdb --xml')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 96, in run
    return xmltodict.parse(''.join(stdout_data))
  File "/opt/HTPC-Manager-0.11.0/libs/xmltodict.py", line 251, in parse
    parser.Parse(xml_input, True)
ExpatError: unclosed token: line 79, column 58

2015-01-15 17:34:40 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:34:40 :: paramiko.transport :: INFO :: Authentication (password) successful!

**Comment by Hellowlol** [comment]
Can you check if that was the last update?

**Comment by smdion** [comment]
Up to date and fresh restart, same error.

**Comment by smdion** [comment]
wait.. had other window open.  I have graphs.

**Comment by Hellowlol** [comment]
zomg! well i have manually pasted the data in.. can you update one last time and try again (i mean it this time lol..)

**Comment by smdion** [comment]
....
2015-01-15 17:46:30 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:46:30 :: paramiko.transport :: INFO :: Authentication (password) successful!
2015-01-15 17:46:30 :: cherrypy.error.47873907871952 :: ERROR :: [15/Jan/2015:17:46:30] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager-0.11.0/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 188, in dumpdb
    return self.run('--dumpdb --xml')
  File "/opt/HTPC-Manager-0.11.0/modules/vnstat.py", line 97, in run
    return xmltodict.parse(shit.strip())
  File "/opt/HTPC-Manager-0.11.0/libs/xmltodict.py", line 251, in parse
    parser.Parse(xml_input, True)
ExpatError: unclosed token: line 79, column 58

2015-01-15 17:46:30 :: paramiko.transport :: INFO :: Connected (version 2.0, client OpenSSH_5.4p1_hpn13v11)
2015-01-15 17:46:30 :: paramiko.transport :: INFO :: Authentication (password) successful!

**Comment by Hellowlol** [comment]
Thanks for trying atleast!

**Comment by Hellowlol** [comment]
@smdion when you have the change can you update and find xml stout_data in the log paste that somewhere. I really wish i could update unraid now...

**Comment by smdion** [comment]
Can you point me in the right direction?

**Comment by Hellowlol** [comment]
Can do, update htpc manger, delete log. visit the vnstat page, change the drown to debug, ctrl f in your browser. you should see a list like this.
'''
['<vnstat version="1.11" xmlversion="1">\n <interface id="eth0">\n <id>eth0</id>\n <nick>eth0</nick>\n <created><date><year>2015</year><month>01</month><day>09</day></date></created>\n <updated><date><year>2015</year><month>01</month><day>16</day></date><time><hour>02</hour><minute>08</minute></time></updated>\n <traffic>\n <total><rx>180260</rx><tx>7937</tx></total>\n <days>\n <day id="0"><date><year>2015</year><month>01</month><day>16</day></date><rx>7860</rx><tx>3410</tx></day>\n <day id="1"><date><year>2015</year><month>01</month><day>15</day></date><rx>22575</rx><tx>1853</tx></day>\n <day id="2"><date><year>2015</year><month>01</month><day>14</day></date><rx>6936</rx><tx>199</tx></day>\n <day id="3"><date><year>2015</year><month>01</month><day>13</day></date><rx>3535</rx><tx>49</tx></day>\n <day id="4"><date><year>2015</year><month>01</month><day>12</day></date><rx>4237</rx><tx>52</tx></day>\n <day id="5"><date><year>2015</year><month>01</month><day>11</day></date><rx>4695</rx><tx>115</tx></day>\n <day id="6"><date><year>2015</year><month>01</month><day>10</day></date><rx>5021</rx><tx>147</tx></day>\n <day id="7"><date><year>2015</year><month>01</month><day>09</day></date><rx>125401</rx><tx>2112</tx></day>\n </days>\n <months>\n <month id="0"><date><year>2015</year><month>01</month></date><rx>180260</rx><tx>7937</tx></month>\n </months>\n <tops>\n <top id="0"><date><year>2015</year><month>01</month><day>09</day></date><time><hour>21</hour><minute>16</minute></time><rx>125401</rx><tx>2112</tx></top>\n <top id="1"><date><year>2015</year><month>01</month><day>15</day></date><time><hour>00</hour><minute>00</minute></time><rx>22575</rx><tx>1853</tx></top>\n <top id="2"><date><year>2015</year><month>01</month><day>14</day></date><time><hour>00</hour><minute>00</minute></time><rx>6936</rx><tx>199</tx></top>\n <top id="3"><date><year>2015</year><month>01</month><day>10</day></date><time><hour>00</hour><minute>00</minute></time><rx>5021</rx><tx>147</tx></top>\n <top id="4"><date><year>2015</year><month>01</month><day>11</day></date><time><hour>00</hour><minute>00</minute></time><rx>4695</rx><tx>115</tx></top>\n <top id="5"><date><year>2015</year><month>01</month><day>12</day></date><time><hour>00</hour><minute>00</minute></time><rx>4237</rx><tx>52</tx></top>\n <top id="6"><date><year>2015</year><month>01</month><day>13</day></date><time><hour>00</hour><minute>00</minute></time><rx>3535</rx><tx>49</tx></top>\n </tops>\n <hours>\n <hour id="0"><date><year>2015</year><month>01</month><day>16</day></date><rx>7273</rx><tx>482</tx></hour>\n <hour id="1"><date><year>2015</year><month>01</month><day>16</day></date><rx>377</rx><tx>2166</tx></hour>\n <hour id="2"><date><year>2015</year><month>01</month><day>16</day></date><rx>210</rx><tx>762</tx></hour>\n <hour id="3"><date><year>2015</year><month>01</month><day>15</day></date><rx>127</rx><tx>2</tx></hour>\n <hour id="4"><date><year>2015</year><month>01</month><day>15</day></date><rx>127</rx><tx>2</tx></hour>\n <hour id="5"><date><year>2015</year><month>01</month><day>15</day></date><rx>126</rx><tx>3</tx></hour>\n <hour id="6"><date><year>2015</year><month>01</month><day>15</day></date><rx>125</rx><tx>1</tx></hour>\n <hour id="7"><date><year>2015</year><month>01</month><day>15</day></date><rx>150</rx><tx>2</tx></hour>\n <hour id="8"><date><year>2015</year><month>01</month><day>15</day></date><rx>181</rx><tx>3</tx></hour>\n <hour id="9"><date><year>2015</year><month>01</month><day>15</day></date><rx>180</rx><tx>2</tx></hour>\n <hour id="10"><date><year>2015</year><month>01</month><day>15</day></date><rx>180</rx><tx>2</tx></hour>\n <hour id="11"><date><year>2015</year><month>01</month><day>15</day></date><rx>180</rx><tx>2</tx></hour>\n <hour id="12"><date><year>2015</year><month>01</month><day>15</day></date><rx>181</rx><tx>2</tx></hour>\n <hour id="13"><date><year>2015</year><month>01</month><day>15</day></date><rx>181</rx><tx>2</tx></hour>\n <hour id="14"><date><year>2015</year><month>01</month><day>15</day></date><rx>', '178</rx><tx>2</tx></hour>\n <hour id="15"><date><year>2015</year><month>01</month><day>15</day></date><rx>181</rx><tx>2</tx></hour>\n <hour id="16"><date><year>2015</year><month>01</month><day>15</day></date><rx>180</rx><tx>2</tx></hour>\n <hour id="17"><date><year>2015</year><month>01</month><day>15</day></date><rx>180</rx><tx>2</tx></hour>\n <hour id="18"><date><year>2015</year><month>01</month><day>15</day></date><rx>183</rx><tx>2</tx></hour>\n <hour id="19"><date><year>2015</year><month>01</month><day>15</day></date><rx>184</rx><tx>2</tx></hour>\n <hour id="20"><date><year>2015</year><month>01</month><day>15</day></date><rx>191</rx><tx>2</tx></hour>\n <hour id="21"><date><year>2015</year><month>01</month><day>15</day></date><rx>224</rx><tx>108</tx></hour>\n <hour id="22"><date><year>2015</year><month>01</month><day>15</day></date><rx>272</rx><tx>285</tx></hour>\n <hour id="23"><date><year>2015</year><month>01</month><day>15</day></date><rx>18541</rx><tx>1417</tx></hour>\n </hours>\n </traffic>\n </interface>\n</vnstat>\n']
'''
copy that one

**Comment by elRadix** [comment]
does not work, running both vnstat and htpc on local machine i get no outpout / no error log

when trying the ssh option i get the following error 
```
2015-01-16 14:58:55 :: cherrypy.error.141233580 :: ERROR :: [16/Jan/2015:14:58:55] HTTP Traceback (most recent call last):
  File "/opt/HTPC-Manager/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/HTPC-Manager/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/HTPC-Manager/libs/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/HTPC-Manager/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/HTPC-Manager/modules/vnstat.py", line 203, in dumpdb
    return self.run('--dumpdb --xml')
  File "/opt/HTPC-Manager/modules/vnstat.py", line 75, in run
    client = paramiko.Transport((hostname, port))
NameError: global name 'paramiko' is not defined
```

I am running vnStat 1.12, thus running the command "vnstat --exportdb --xml" on the loca lmachine works as you can see on this output 
http://pastebin.com/EpiA5bgg

**Comment by Hellowlol** [comment]
@elRadix you need to use the ssh option and install paramiko for now, I have disabled the rest to make debugging easier.

**Comment by elRadix** [comment]
installed paramiko as suggested and it works, just needs to tweaks regarding the presentation of the graphic/titles

![Image of vnstat running on htpc]
(http://i60.tinypic.com/5n7w2r.png)

**Comment by Hellowlol** [comment]
Nice! I think there are some issues drawing the graphics, if you only have one interface is looks nice.

**Comment by smdion** [comment]
I'm still having issues. I'll update to 1.12 and see if that fixes it.

**Comment by smdion** [comment]
I ran went to http://myip:8085/manager/vnstat/dumpdb and the first two times I loaded the page I got a Internal Server Error, 3rd time I got this

http://pastebin.com/3UMS7Srh

**Comment by Hellowlol** [comment]
Oki could you find xml stout_data in the log? I should be a list. It contains the stout before its parsed by xmltodict. I needed that to figure out why it fails.

**Comment by smdion** [comment]
unless i'm just being daft.. which is possible. I can't get it to show debug logs

**Comment by smdion** [comment]
TIL I have to start HTPC-Manager in debug mode  /facepalm

http://pastebin.com/TC7CrP7F

**Comment by Hellowlol** [comment]
Yeah, sorry about that.. I just forgot to mention it as mine always run in --debug :P

**Comment by Hellowlol** [comment]
@smdion are you running the latest version? i thought i disabled the paramiko log.

**Comment by smdion** [comment]
Nope... now I am.

http://pastebin.com/ZBvcrSQE

**Comment by Hellowlol** [comment]
Lets try to read the entire files instead of streaming it. Can you update and try again?

**Comment by smdion** [comment]
that did it.

**Comment by Hellowlol** [comment]
Wow, thanks for your patience.

**Comment by smdion** [comment]
Thanks for your hard work!

http://i.imgur.com/UDJHpfs.png

Just to make sure its as you expect.

**Comment by Hellowlol** [comment]
It isnt, can you force browser cache?

**Comment by smdion** [comment]
http://i.imgur.com/4UZrM7Z.png

**Comment by Hellowlol** [comment]
The graphs seems very high, are they correct? :o

**Comment by smdion** [comment]
No.. they seem wrong to me too.  Other bandwidth monitor

4.65 GB today
315 GB this month
942 GB last month

**Comment by Hellowlol** [comment]
Alright, can you --dumpdb --xml i need to manually check your xml to see what i fucked up. My first thought was zomg I want your internet speed. I knew is was to good to be true.. :P

**Comment by smdion** [comment]
http://pastebin.com/LhmK6pzL

**Comment by Hellowlol** [comment]
I think they are correct, i just forgot to change the label from tb to gibi

**Comment by smdion** [comment]
I was going to say... they look 2 decimal places off.  Really nice work.  Any way you could do a "Today", "This Month" "Last Month" summary in text?  kinda like this? 

http://imgur.com/SB9CvjO

**Comment by Hellowlol** [comment]
Can do

**Comment by smdion** [comment]
You are incredibly awesome.

**Comment by smdion** [comment]
Also... is the bandwidth suppose to auto update (at top of page) or only on page refresh?

**Comment by Hellowlol** [comment]
That current bandwith will auto update, but not the graphs/tables.

**Comment by Hellowlol** [comment]
The good news is that the table is done, bad news is that everything is fucked up. I can't belive I forgot that json is unordered..

**Comment by Hellowlol** [comment]
@elRadix @smdion Can you update take it for a spin? its only minor codecleanup left..

**Comment by smdion** [comment]
Looks good to me. https://imgur.com/VlRlFbx  And bandwidth now auto updates.

**Comment by Hellowlol** [comment]
Awesome. Do you want something on the dash aswell? Only thing left is add what interface your looking on and remove the x and cleanup.

**Comment by smdion** [comment]
I can't think of anything on the dashboard..... maybe the current bandwidth usage?  Not anything I really really want.  This is so awesome, I can turn off my UpStatsBoard now.  Thank you!

**Comment by Hellowlol** [comment]
Okei, I think in gonna leave it as it is. Down the road I want to add a quick system overview on the dashbord with current speed, vs bandwidth cap, memory and cpu. Thank you for assisting me debugging. This module wouldn't exist without your help! I'll clean up and merge it with master2 later today.

**Comment by smdion** [comment]
I did notice one thing. The word period Is misspelled on the text part of
the summary

**Comment by Hellowlol** [comment]
Thanks! Is spelled correct, but in the wrong language.

**Comment by smdion** [comment]
What do you mean... English is the only language ;)

**Comment by Hellowlol** [comment]
merged
