### ISSUE TITLE
FreeNAS / FreeBSD issues

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#95]
Trying to manually install HTPC-Manager in a jail:

     1	21:25	pkg update
     2	21:26	pkg upgrade
     7	21:29	git clone https://github.com/Hellowlol/HTPC-Manager.git
     8	21:30	ls
     9	21:30	cd HTPC-Manager/
    10	21:30	git pull
    11	21:30	ls -l
    12	21:30	python Htpc.py
    13	21:30	./Htpc.py
    14	21:33	exit
    15	21:34	pkg install python
    16	21:34	HTPC-Manager/Htpc.py
    17	21:34	python HTPC-Manager/Htpc.py

Here is the error I get:
Traceback (most recent call last):
  File "HTPC-Manager/Htpc.py", line 241, in <module>
    main()
  File "HTPC-Manager/Htpc.py", line 167, in main
    htpc.settings = Settings()
  File "/HTPC-Manager/htpc/settings.py", line 29, in __init__
    sqlhub.processConnection = connectionForURI('sqlite:' + htpc.DB)
  File "/HTPC-Manager/libs/sqlobject/dbconnection.py", line 1011, in connectionForURI
    conn = connCls.connectionFromURI(uri)
  File "/HTPC-Manager/libs/sqlobject/dbconnection.py", line 138, in connectionFromURI
    return cls._connectionFromParams(*cls._parseURI(uri))
  File "/HTPC-Manager/libs/sqlobject/sqlite/sqliteconnection.py", line 105, in _connectionFromParams
    return cls(filename=path, **args)
  File "/HTPC-Manager/libs/sqlobject/sqlite/sqliteconnection.py", line 48, in __init__
    raise ImportError('Cannot find an SQLite driver, tried %s' % drivers)
ImportError: Cannot find an SQLite driver, tried pysqlite2,sqlite3,sqlite
Exception AttributeError: "SQLiteConnection instance has no attribute '_memory'" in <bound method SQLiteConnection.__del__ of <sqlobject.sqlite.sqliteconnection.SQLiteConnection instance at 0x8067ebd88>> ignored

Please advise.

**Comment by Hellowlol** [comment]
I dont think you can install from source. You can find a example of a plugin here https://github.com/josh4trunks/freenas-plugins. 

I know nothing about freenas, your likely to have much better luck asking on the freenas forum.
